config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'pages/index'

  get 'pages/about'

  get 'pages/catalog'

  get 'pages/samples'

  get 'pages/faq'

  get 'pages/contact'

  devise_for :users
  
  
  root 'pages#index'
  
  
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
         can :access, :rails_admin       # only allow admin users to access Rails Admin
         can :dashboard
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def catalog
  end

  def samples
  end

  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <div class="container">
        <div class="navbar-left">
            <%= link_to root_path, class: "navgar-brand" do %>
                <%= image_tag "just-cool-socks.jpg", class: "img-responsive", style: "width: 100px; padding: 4px 0px 4px 0px;" %>
            <% end %>    
        </div>
        
        <ul class="nav navbar-nav navbar-right margin-top-nav">
            <li><%= link_to 'HOME', root_path %></li>
            <li><%= link_to 'ABOUT US', pages_about_path %></li>
            <li><%= link_to 'CATALOG', pages_catalog_path %></li>
            <li><%= link_to 'SAMPLES', pages_samples_path %></li>
            <li><%= link_to 'FAQ', pages_faq_path %></li>
            <li><%= link_to 'CONTACT US', pages_contact_path %></li>
            <% if user_signed_in? %>
                <li><%= link_to('LOGOUT', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
                <li><%= link_to('LOGIN', new_user_session_path)  %></li>
            <% end %>
        </ul>  
    </div>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Just Cool Socks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/catalog.html.erb
<h1>Pages#catalog</h1>
<p>Find me in app/views/pages/catalog.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/index.html.erb
<div class="row margin-top-50">
    <div class="col-md-8">
        <iframe src="https://player.vimeo.com/video/141078111" width="100%" height="420" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
    <div class="col-md-4">
        <h3>Why Just Cool Socks?</h3>
        <p>Because you are the boss and not our customer. It is our promise to you that we will mail you socks that we think you will enjoy. If you are not satisfied send the socks back and we will send you a new pair. Lastly, we are a social-entrepreneurship that supports causes in our community. Our current focus is Aunt Leah’s Place, a non-profit that supports foster children, homeless youth, and mothers’ in-need. www.auntleahs.org</p>
    </div>
</div>

<div class="row margin-top-50">
    <div class="col-md-12">
        <h2>How It Works?</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <%= image_tag 'point-1-350.jpg', class: 'img-responsive' %>
    </div>
    <div class="col-md-4">
        <%= image_tag 'point-2-350.jpg', class: 'img-responsive' %>
    </div>
    <div class="col-md-4">
        <%= image_tag 'point-3-350.jpg', class: 'img-responsive' %>
    </div>
</div>

<div class="row margin-top-50">
    <div class="col-md-12 text-center">
        <h2>Our Cool Socks</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-3">
        <%= image_tag "GIft-350x435.jpg", class: "img-responsive" %>
        <small>Six Month Gift Subscription - $65.00</small>
    </div>
    <div class="col-md-3">
        <%= image_tag "Six-month-350x435.jpg", class: "img-responsive" %>
        <small>Six Month Sock Subscription - From $65.00 every 6 months</small>
    </div>
    <div class="col-md-3">
        <%= image_tag "cool-socks_project-2_11-350x435.jpg", class: "img-responsive" %>
        <small>Month to Month Subscription - $13 / month</small>
    </div>
    <div class="col-md-3">
        <%= image_tag "One-Year-350x435.jpg", class: "img-responsive" %>
        <small>One Year Sock Subscription - $120 / year</small>
    </div>
</div>

app/views/pages/samples.html.erb
<h1>Pages#samples</h1>
<p>Find me in app/views/pages/samples.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>